export enum HighlightLanguages {
    bash = `bash`,
    cSharp = `csharp`,
    css = `css`,
    html = `xml`,
    javascript = `javascript`,
    json = `json`,
    markdown = `markdown`,
    plaintext = `plaintext`,
    powershell = `powershell`,
    scss = `scss`,
    shell = `shell`,
    sql = `sql`,
    typescript = `typescript`,
    xml = `xml`,
}